language: python

python:
  - "2.7"

install:
  - pip install --editable . # Install it self
  - pip install -r requirements-test.txt # Install test dependencies

script:
  - pytest tests --cov=afwf_fts_anything # Run unittest

notifications:
  email: false # Mute email notification
